import React,{useState} from 'react';
import {useGame} from '../context/GameContext';
import {Sparkles,CheckCircle2,Flame,Award,Zap,ArrowRight} from 'lucide-react';

export const LandingView:React.FC=()=>{
 const {loginWithGoogle}=useGame(); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const signIn=async()=>{setError('');setLoading(true);try{await loginWithGoogle()}catch(e:any){setError(e?.message||'Google Sign-In failed. Please try again.')}finally{setLoading(false)}};
 return <div className="min-h-screen bg-[#090a0f] text-slate-100 flex flex-col justify-between relative overflow-hidden">
  <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-violet-600/15 rounded-full blur-[120px] pointer-events-none"/><div className="absolute bottom-[-10%] right-[-10%] w-[600px] h-[600px] bg-indigo-600/15 rounded-full blur-[140px] pointer-events-none"/>
  <header className="px-6 py-5 max-w-7xl mx-auto w-full flex items-center relative z-10"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-violet-600 to-indigo-500 flex items-center justify-center shadow-[0_0_20px_rgba(139,92,246,0.6)]"><Zap className="w-5 h-5 fill-white"/></div><div><h1 className="font-extrabold text-xl tracking-wider">QUESTORA</h1><p className="text-[10px] text-violet-400 font-medium">Level Up Your Real Life</p></div></div></header>
  <main className="max-w-7xl mx-auto w-full px-6 py-12 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center relative z-10">
   <div className="lg:col-span-7 space-y-6"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-violet-950/60 border border-violet-500/40 text-violet-300 text-xs font-mono font-semibold"><Sparkles className="w-3.5 h-3.5"/>GAMIFIED PERSONAL PROGRESSION PLATFORM</div><h1 className="text-4xl sm:text-5xl xl:text-6xl font-black tracking-tight leading-none text-white">YOUR LIFE.<br/><span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-indigo-300 to-amber-300">YOUR QUEST.</span><br/>YOUR CHARACTER.</h1><p className="text-slate-300 text-base sm:text-lg max-w-xl leading-relaxed">Turn everyday real-world goals into quests, earn XP & Gold, build attributes, maintain streaks, and watch your virtual RPG character evolve.</p><div className="grid grid-cols-3 gap-3 pt-4 border-t border-violet-900/30 max-w-lg"><div className="p-3 rounded-2xl bg-slate-900/60 border border-slate-800"><CheckCircle2 className="w-5 h-5 text-violet-400 mb-1"/><h4 className="text-xs font-bold">Real Actions</h4><p className="text-[11px] text-slate-400">Complete quests</p></div><div className="p-3 rounded-2xl bg-slate-900/60 border border-slate-800"><Flame className="w-5 h-5 text-orange-400 mb-1"/><h4 className="text-xs font-bold">Earn XP & Gold</h4><p className="text-[11px] text-slate-400">Non-linear leveling</p></div><div className="p-3 rounded-2xl bg-slate-900/60 border border-slate-800"><Award className="w-5 h-5 text-amber-400 mb-1"/><h4 className="text-xs font-bold">Unlock Rewards</h4><p className="text-[11px] text-slate-400">Cosmetic gear</p></div></div></div>
   <div className="lg:col-span-5 bg-[#10121a]/90 backdrop-blur-xl border border-violet-900/40 rounded-3xl p-8 shadow-[0_0_50px_rgba(139,92,246,0.15)]"><h2 className="text-xl font-bold mb-2">START YOUR JOURNEY</h2><p className="text-sm text-slate-400 mb-6">Sign in securely with your Google account. Your progression is stored in Firestore and follows you across devices.</p>{error&&<div role="alert" className="mb-4 p-3 rounded-xl bg-rose-950/60 border border-rose-800/60 text-rose-300 text-xs">{error}</div>}<button onClick={signIn} disabled={loading} className="w-full flex items-center justify-center gap-3 bg-white hover:bg-slate-100 text-slate-900 font-bold py-3.5 rounded-xl shadow-lg transition-all disabled:opacity-50"><span className="text-lg">G</span><span>{loading?'CONNECTING...':'CONTINUE WITH GOOGLE'}</span><ArrowRight className="w-4 h-4"/></button><p className="text-[11px] text-slate-500 text-center mt-5">Google OAuth • Secure authentication • Cloud persistence</p></div>
  </main><footer className="px-6 py-4 border-t border-violet-900/20 text-center text-xs text-slate-500 relative z-10">QUESTORA — Level Up Your Real Life.</footer>
 </div>;
};
